# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82e4254bd0c93c9dfaa335fb1ce7c1f75d44d870a4594340b9837843b5171efa05330ac17f6bf97d933824104618081248f74df2c58df5be2e22244f4b28d965

test:
  secret_key_base: 863bdf4146693ee494fcba6975e76eba604361e91115c423435a8d113635df1225935115559458288d713952a3e558fc154efa4119e3fcbe482a486e520136cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9d933e04fb4089c3aa1849c4c3f64d5adaf2c8110515396bd90f5139a71c96dfdd9248c49fb63eae87a5e0977621a28db45ea69c4a99e81a7e0fb0f8855ef65f